### ISSUE TITLE
你好，如何才能纯js引入，不用npm install

### ISSUE THREAD

**Issue by lovecodeyou** [ADKcodeXD/Vue3-Emoji#1]
1. 比如像 elementuiplus vue3 一样提供了 js的引入方式

[elementui](https://element-plus.gitee.io/zh-CN/guide/installation.html#unpkg)

[vue3](https://cn.vuejs.org/guide/quick-start.html#using-vue-from-cdn)

**Comment by ADKcodeXD** [comment]
这个目前我暂时没有去做，后面会研究下的。
