### ISSUE TITLE
不算bug的bug，能用，但是报错

### ISSUE THREAD

**Issue by babizhu** [ADKcodeXD/Vue3-Emoji#10]
版本：
"vue": "^3.4.20",
    "vue-i18n": "^9.9.1",
    "vue-router": "^4.3.0",
    "vue3-emoji": "^2.1.8",
使用方法
    <V3Emoji />
点击打开表情面板的时候，能显示，但是报错如下：
runtime-core.esm-bundler.js:44  [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 
  at <PollUp key=0 onClickEmoji=fn<q> size="mid"  ... > 
  at <V3Emoji onClickEmoji=undefined recent=true custom-size=undefined > 
  at <Index> 
  at <NewCustomerMarketingActions onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > key="/configuration/newCustomerMarketingActions" > 
  at <KeepAlive key=0 include= [] > 
  at <BaseTransition mode="out-in" appear=true persisted=false  ... > 
  at <Transition appear="" name="slide-fadein-right" mode="out-in" > 
  at <RouterView> 
  at <ParentCompConsumer> 
  at <RouteView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent class="ant-pro-basicLayout-content" flex="" flex-col="" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <BasicLayout collapsed=false theme="light" menu-data= (5) [{…}, {…}, {…}, {…}, {…}]  ... > 
  at <ProLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <TokenProvider> 
  at <AApp class="h-full font-chinese antialiased" > 
  at <Anonymous value= {hashed: true, components: {…}, theme: Theme, token: {…}} > 
  at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider theme= {token: {…}, components: {…}, algorithm: ƒ} locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:44
logError @ runtime-core.esm-bundler.js:249
handleError @ runtime-core.esm-bundler.js:241
callWithErrorHandling @ runtime-core.esm-bundler.js:194
flushJobs @ runtime-core.esm-bundler.js:399
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:308
queueJob @ runtime-core.esm-bundler.js:302
(匿名) @ runtime-core.esm-bundler.js:6126
resetScheduling @ reactivity.esm-bundler.js:264
triggerEffects @ reactivity.esm-bundler.js:308
triggerRefValue @ reactivity.esm-bundler.js:1075
set value @ reactivity.esm-bundler.js:1120
e.textArea.createBaseVNode.onClick.s.<computed>.s.<computed> @ Vue3Emoji.es.js:15526
callWithErrorHandling @ runtime-core.esm-bundler.js:192
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:199
invoker @ runtime-dom.esm-bundler.js:693
显示 17 更多框架
显示简略信息
runtime-core.esm-bundler.js:5711  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'el')
    at patchBlockChildren (runtime-core.esm-bundler.js:5711:18)
    at processFragment (runtime-core.esm-bundler.js:5812:9)
    at patch (runtime-core.esm-bundler.js:5306:9)
    at patchBlockChildren (runtime-core.esm-bundler.js:5722:7)
    at patchElement (runtime-core.esm-bundler.js:5614:7)
    at processElement (runtime-core.esm-bundler.js:5463:7)
    at patch (runtime-core.esm-bundler.js:5320:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6088:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6132:16)
patchBlockChildren @ runtime-core.esm-bundler.js:5711
processFragment @ runtime-core.esm-bundler.js:5812
patch @ runtime-core.esm-bundler.js:5306
patchBlockChildren @ runtime-core.esm-bundler.js:5722
patchElement @ runtime-core.esm-bundler.js:5614
processElement @ runtime-core.esm-bundler.js:5463
patch @ runtime-core.esm-bundler.js:5320
componentUpdateFn @ runtime-core.esm-bundler.js:6088
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:6132
callWithErrorHandling @ runtime-core.esm-bundler.js:192
flushJobs @ runtime-core.esm-bundler.js:399
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:308
queueJob @ runtime-core.esm-bundler.js:302
(匿名) @ runtime-core.esm-bundler.js:6126
resetScheduling @ reactivity.esm-bundler.js:264
triggerEffects @ reactivity.esm-bundler.js:308
triggerRefValue @ reactivity.esm-bundler.js:1075
set value @ reactivity.esm-bundler.js:1120
e.textArea.createBaseVNode.onClick.s.<computed>.s.<computed> @ Vue3Emoji.es.js:15526
callWithErrorHandling @ runtime-core.esm-bundler.js:192
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:199
invoker @ runtime-dom.esm-bundler.js:693
显示 24 更多框架
显示简略信息
runtime-core.esm-bundler.js:44  [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core . 
  at <PollUp key=0 onClickEmoji=fn<q> size="mid"  ... > 
  at <V3Emoji onClickEmoji=undefined recent=true custom-size=undefined > 
  at <Index> 
  at <NewCustomerMarketingActions onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > key="/configuration/newCustomerMarketingActions" > 
  at <KeepAlive key=0 include= [] > 
  at <BaseTransition mode="out-in" appear=true persisted=false  ... > 
  at <Transition appear="" name="slide-fadein-right" mode="out-in" > 
  at <RouterView> 
  at <ParentCompConsumer> 
  at <RouteView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent class="ant-pro-basicLayout-content" flex="" flex-col="" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <BasicLayout collapsed=false theme="light" menu-data= (5) [{…}, {…}, {…}, {…}, {…}]  ... > 
  at <ProLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <TokenProvider> 
  at <AApp class="h-full font-chinese antialiased" > 
  at <Anonymous value= {hashed: true, components: {…}, theme: Theme, token: {…}} > 
  at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider theme= {token: {…}, components: {…}, algorithm: ƒ} locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>
warn$1 @ runtime-core.esm-bundler.js:44
logError @ runtime-core.esm-bundler.js:249
handleError @ runtime-core.esm-bundler.js:241
callWithErrorHandling @ runtime-core.esm-bundler.js:194
flushJobs @ runtime-core.esm-bundler.js:399
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:308
queueJob @ runtime-core.esm-bundler.js:302
(匿名) @ runtime-core.esm-bundler.js:6126
resetScheduling @ reactivity.esm-bundler.js:264
triggerEffects @ reactivity.esm-bundler.js:308
triggerRefValue @ reactivity.esm-bundler.js:1075
set value @ reactivity.esm-bundler.js:1120
oe @ Vue3Emoji.es.js:15256
(匿名) @ Vue3Emoji.es.js:15296
显示 14 更多框架
显示简略信息
runtime-dom.esm-bundler.js:654  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'Symbol(_vei)')
    at patchEvent (runtime-dom.esm-bundler.js:654:20)
    at patchProp (runtime-dom.esm-bundler.js:727:7)
    at patchElement (runtime-core.esm-bundler.js:5666:15)
    at processElement (runtime-core.esm-bundler.js:5463:7)
    at patch (runtime-core.esm-bundler.js:5320:11)
    at patchBlockChildren (runtime-core.esm-bundler.js:5722:7)
    at processFragment (runtime-core.esm-bundler.js:5812:9)
    at patch (runtime-core.esm-bundler.js:5306:9)
    at patchBlockChildren (runtime-core.esm-bundler.js:5722:7)
    at patchElement (runtime-core.esm-bundler.js:5614:7)
patchEvent @ runtime-dom.esm-bundler.js:654
patchProp @ runtime-dom.esm-bundler.js:727
patchElement @ runtime-core.esm-bundler.js:5666
processElement @ runtime-core.esm-bundler.js:5463
patch @ runtime-core.esm-bundler.js:5320
patchBlockChildren @ runtime-core.esm-bundler.js:5722
processFragment @ runtime-core.esm-bundler.js:5812
patch @ runtime-core.esm-bundler.js:5306
patchBlockChildren @ runtime-core.esm-bundler.js:5722
patchElement @ runtime-core.esm-bundler.js:5614
processElement @ runtime-core.esm-bundler.js:5463
patch @ runtime-core.esm-bundler.js:5320
componentUpdateFn @ runtime-core.esm-bundler.js:6088
run @ reactivity.esm-bundler.js:177
instance.update @ runtime-core.esm-bundler.js:6132
callWithErrorHandling @ runtime-core.esm-bundler.js:192
flushJobs @ runtime-core.esm-bundler.js:399
Promise.then(异步)
queueFlush @ runtime-core.esm-bundler.js:308
queueJob @ runtime-core.esm-bundler.js:302
(匿名) @ runtime-core.esm-bundler.js:6126
resetScheduling @ reactivity.esm-bundler.js:264
triggerEffects @ reactivity.esm-bundler.js:308
triggerRefValue @ reactivity.esm-bundler.js:1075
set value @ reactivity.esm-bundler.js:1120
oe @ Vue3Emoji.es.js:15256
(匿名) @ Vue3Emoji.es.js:15296
显示 26 更多框架
显示简略信息

**Comment by ADKcodeXD** [comment]
收到您的反馈~

**Comment by hardstylewyl** [comment]
同问

**Comment by lzlife** [comment]
> 收到您的反馈~

加1

**Comment by EvenDBL** [comment]
同问

**Comment by T97-coffee** [comment]
+1 TypeError: Cannot read properties of null (reading 'Symbol(_vei)')

**Comment by T97-coffee** [comment]
发现这个bug的一个副作用，这个bug报错导致我的项目中路由失效，回退到2.0.0版本没有报错了了，路由也正常了
