### ISSUE TITLE
fix-pos不管用？

### ISSUE THREAD

**Issue by T97-coffee** [ADKcodeXD/Vue3-Emoji#11]
`<V3Emoji
    fix-pos="upcenter"
    :customTab="customTab"
    :disable-group="disableGroup"
    v-bind="$attrs"
  />`和`<V3Emoji
    fixPos="upcenter"
    :customTab="customTab"
    :disable-group="disableGroup"
    v-bind="$attrs"
  />`都没起作用，弹出框的位置还是随机出现在上面或者下面？

**Comment by ppepenpeng** [comment]
+1
