### ISSUE TITLE
打开表情面板时报错

### ISSUE THREAD

**Issue by GoldenFlash0927** [ADKcodeXD/Vue3-Emoji#13]
![微信图片_20240710154439](https://github.com/ADKcodeXD/Vue3-Emoji/assets/78634776/2ade75f7-5cae-4d01-89ea-8d53a549770a)
你好， 打开面板时会报el错误，切换面板时会报下面那两个错

**Comment by wins-lcy** [comment]
+1 如何解决

**Comment by ppepenpeng** [comment]
+1
