### ISSUE TITLE
3,0版本样式好像混乱了，不知道是不是我操作的问题

### ISSUE THREAD

**Issue by ppepenpeng** [ADKcodeXD/Vue3-Emoji#14]
感谢作者的更新。
这个是我用npm装3.0版本的情况
![image](https://github.com/user-attachments/assets/c5761c74-e148-4410-a6f1-0c4b9487a8e4)

我把2.0的包卸载了，装了3.0的，
![image](https://github.com/user-attachments/assets/1e94a697-1e0a-48b5-8609-14ec7fcda3b6)

然后重启项目后 样式就乱掉了，恢复回2.0样式又可以了

**Comment by ppepenpeng** [comment]
![image](https://github.com/user-attachments/assets/f839a754-7345-404e-b624-3bc94161e681)
这是我的依赖

![image](https://github.com/user-attachments/assets/b0b43495-481e-4456-84bd-264b8d1f5e1f)
控制台报了一个警告

**Comment by ADKcodeXD** [comment]
好的今晚看一下
