### ISSUE TITLE
package.json配置优化问题

### ISSUE THREAD

**Issue by wu464818763** [ADKcodeXD/Vue3-Emoji#15]
package.json中的exports配置的路径能否指定为相对路径？

**Comment by wu464818763** [comment]
将“dist/Vue3Emoji.es.js”与“dist/Vue3Emoji.umd.js”修改为“./dist/Vue3Emoji.es.js”与“./dist/Vue3Emoji.umd.js”，不然在一些依赖项目构建时会报错：Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/Vue3Emoji.es.js" defined in the package config E:\portal-web-components-demo\node_modules\.pnpm\@aec-admin+components-lib@0.5.60_@wangeditor+editor-for-vue@5.1.12_@wangeditor+editor@5.1.23__pg26u3vu3rusit4hsfchpvim7u\node_modules\vue3-emoji\package.json imported from E:\portal-web-components-demo\node_modules\.pnpm\@aec-admin+components-lib@0.5.60_@wangeditor+editor-for-vue@5.1.12_@wangeditor+editor@5.1.23__pg26u3vu3rusit4hsfchpvim7u\node_modules\@aec-admin\components-lib\dist\lib\game-center\components\Input\EmojiInput.vue2.mjs; targets must start with "./"

**Comment by ADKcodeXD** [comment]
非常感谢您的建议，后续我会跟进的。
