### ISSUE TITLE
About the problem that the emoji list is not closed?

### ISSUE THREAD

**Issue by Zqc925** [ADKcodeXD/Vue3-Emoji#2]
May I ask why the emoji list will not be closed after clicking the emoji, and you need to click the blank space next to it to close it?

**Comment by ADKcodeXD** [comment]
I didn't take this into consideration when I first designed it, and I will consider adding a corresponding configuration item in the next version.

**Comment by Zqc925** [comment]
Now there is a situation of concealment in use. I use position: absolute; Z-index: no matter how many settings are set, most cannot be displayed to the top

**Comment by ADKcodeXD** [comment]
add closePop to control the pannel's open state.
