### ISSUE TITLE
能不能加一个输入框类型？

### ISSUE THREAD

**Issue by 872301800** [ADKcodeXD/Vue3-Emoji#4]
现在的输入框默认是 textarea 不可更改。但是这个多行输入会有滚动条，我想在移动端使用，保持一行 不能换行，不出现滚动条。希望可以加一个输入框类型属性， inputType 之类的  默认是textarea 可更改为input, 。

**Comment by ADKcodeXD** [comment]
收到您的反馈，我会考虑加上的~
