### ISSUE TITLE
@close函数触发异常

### ISSUE THREAD

**Issue by ghost** [ADKcodeXD/Vue3-Emoji#8]
![screenshots](https://github.com/ADKcodeXD/Vue3-Emoji/assets/47898108/27a955f0-3738-4df9-aeab-0e4e021f2fbd)
我这里的input和emoji组件是同级的,点击input会触发emoji关闭事件

**Comment by ADKcodeXD** [comment]
我将在新版本提供手动关闭的配置项以供解决该问题
