### ISSUE TITLE
vue3项目引入报错页面刷新Object(...) is not a function

### ISSUE THREAD

**Issue by code00000001** [ADKcodeXD/Vue3-Emoji#9]
ypeError: Object(...) is not a function
    <anonymous> webpack-internal:///./node_modules/vue3-emoji/dist/Vue3Emoji.es.js:15244
    js http://127.0.0.1:8080/static/js/8.js:205
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/chat/components/BottomServe.vue?vue&type=script&lang=js:9
    js http://127.0.0.1:8080/static/js/8.js:23
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./src/views/chat/components/BottomServe.vue?vue&type=script&lang=js:2
    js http://127.0.0.1:8080/static/js/8.js:288
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./src/views/chat/components/BottomServe.vue:3
    vue http://127.0.0.1:8080/static/js/8.js:276
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/chat/ChatDialog.vue?vue&type=script&lang=js:11
    js http://127.0.0.1:8080/static/js/8.js:11
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./src/views/chat/ChatDialog.vue?vue&type=script&lang=js:2
    js http://127.0.0.1:8080/static/js/8.js:240
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    <anonymous> webpack-internal:///./src/views/chat/ChatDialog.vue:3
    vue http://127.0.0.1:8080/static/js/8.js:228
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    promise callback*component webpack-internal:///./src/router/index.js:105
    extractComponentsGuards webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:2013
    navigate webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:3106
    promise callback*navigate webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:3101
    pushWithRedirect webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:2996
    push webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:2935
    install webpack-internal:///./node_modules/vue-router/dist/vue-router.esm-bundler.js:3312
    use webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3122
    <anonymous> webpack-internal:///./src/main.js:173
    js http://127.0.0.1:8080/static/js/app.js:1155
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    fn http://127.0.0.1:8080/static/js/app.js:151
    1 http://127.0.0.1:8080/static/js/app.js:1204
    __webpack_require__ http://127.0.0.1:8080/static/js/app.js:854
    checkDeferredModules http://127.0.0.1:8080/static/js/app.js:46

**Comment by ADKcodeXD** [comment]
可以提供详细一些的消息吗？
